# Generated by Django 3.1.3 on 2020-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coursesOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=250)),
                ('professorName', models.CharField(max_length=100)),
                ('preRequisites', models.TextField()),
            ],
        ),
    ]
