# Generated by Django 3.1.3 on 2020-11-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEAS_Course_Planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesoffered',
            name='semester',
            field=models.CharField(choices=[('SPR 21', 'SPR 21'), ('FA 21', 'FA 21'), ('SPR 22', 'SPR 22'), ('FA 22', 'FA 22'), ('SPR 23', 'SPR 23'), ('FA 23', 'FA 23'), ('SPR 24 ', 'SPR 24'), ('FA 24', 'FA 24')], default='SPR 21', max_length=20),
        ),
    ]
