# Generated by Django 3.1.3 on 2020-11-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEAS_Course_Planner', '0002_coursesoffered_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesoffered',
            name='degreeProgram',
            field=models.CharField(choices=[('Architectural Science', 'Architectural Science'), ('Civil Engineering', 'Civil Engineering'), ('Computer Information Technology', 'Computer Information Technology'), ('Computer Science', 'Computer Science'), ('Construction Management', 'Construction Management'), ('Electrical Engineering', 'Electrical Engineering'), ('Engineering Technology Management', 'Engineering Technology Management'), ('Manufacturing Engineering Technology', 'Manufacturing Engineering Technology'), ('Mechanical Engineering', 'Mechanical Engineering')], default='Architectural Science', max_length=50),
        ),
    ]
