# Generated by Django 3.1.3 on 2020-11-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEAS_Course_Planner', '0003_coursesoffered_degreeprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesoffered',
            name='professorName',
        ),
    ]
